# README
* Migration PUMAs Database
PostgreSQL database for storing PUMA and migPUMA information. More information about the underlying data can be found at https://www.census.gov/programs-surveys/acs/microdata/documentation.html. This current iteration of the database is based on the 5-year dataset between 2015-2019 conducted from the American Community Survey (ACS) Public Use Microdata Sample (PUMS) https://www2.census.gov/programs-surveys/acs/data/pums/2019/5-Year/. Specifically this dataset includes the person records for all fifty states, Washington D.C., and Puerto Rico.
* PostgreSQL version
PostgreSQL 10.19 (Ubuntu 10.19-0ubuntu0.18.04.1)
* Dependencies
Most of the dependencies for the project are only needed if one wants to build the database from scratch.
** Build from scratch
- ~UNIX/Linux (tested on Ubuntu 18.04)~
  + ~sed (tested on 4.4)~
  + ~cat (tested on 8.28)~
  + ~konwert (tested on 1.8)~
- ~Clojure (tested on 1.10.1)~
- ~Python (tested on 3.6.9)~
- ~PostgreSQL (tested on 10.19)~
- ~psql (tested on 10.19)~
** Build from release
- ~PostgreSQL (tested on 10.19)~
- ~psql (tested on 10.19)~
* Database creation & initialization
** Overview
Converting the CSV files provided by https://www.census.gov/programs-surveys/acs/microdata/access.html into the format ultimately used by this PostgreSQL database involves multiple steps of data preprocessing and transformation. The current iteration of this database is based on the five year individual dataset from years 2015-2019, though this dataset aims to be dynamic in its capacity to be expanded to future releases of individual data. This database is a continuation of the initial work done in https://github.com/qiang-yi/PUMS_migration, thus this Python preprocessing is utilized as an initial step in converting the CSVs to SQL. For convenience, the Python code used from this repository is included locally, given collaboration with the original authors of this repository.
** Build from scratch
*** Database creation
*** Database initialization
** Build from release
The easiest way to get the database up and running is via the included release. Once the release is unzipped and a new database has been created (this example assumes the new database is named ~pumsdb~), run the following to import the database
#+BEGIN_SRC bash
psql -d pumsdb -f pumsdb-dump
#+END_SRC
* Semantics of database attributes
Columns of the tables in the database are based mostly on https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2015-2019.pdf. Column names are made to closely resemble their original names in this data dictionary, where applicable. There are general tendencies for converting between the ranges of the values present in the original columns of the CSVs and the respective attributes in the associated SQL tables, for example, boolean/predicate columns in the data dictionary are represented by
#+BEGIN_EXAMPLE
b N/A
1 Yes
2 No
#+END_EXAMPLE
such that
# turns out haskell syntax highlighting looks pretty good for this little
# mapping example
#+BEGIN_SRC haskell
b => NULL
1 => true
2 => false
#+END_SRC
This is more inline with SQL data types, especially given SQL's support for ternary boolean logic (a bool b in SQL is either true, false, or NULL). This change allows for space and time complexity optimizations over using a numeric type to represent these values.
* Future work
Given the Census' record of changing pumas in accordance with the census conducted each ten years (as they have in 2000 and 2010). Inclusion of future years' data may require reworking queries and the database itself, rather than simply being able to preprocess the data using the included scripts and then inserting the resultant CSV files into the existing database. This should be possible for expanding the database to include data from previous years, such as the 2010-2014 five year dataset not currently included.
